services:
  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: crud_api
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      TZ: America/Lima
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  api:
    build: ./backend
    container_name: api
    environment:
      PORT: 3001
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: crud_api
      DB_USER: admin
      DB_PASS: 123456
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      - db
    ports:
      - "3001:3001"

  web:
    build: ./frontend
    container_name: web
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  db_data:
